/**
 * US state-level food industry data — manufacturing, agriculture, organic farms,
 * FDA-registered facilities, and local specialty foods.
 *
 * Sources: USDA Census of Agriculture, FDA Registered Food Facilities,
 * USDA Organic Integrity Database, Bureau of Labor Statistics.
 */

export interface StateData {
  slug: string;
  name: string;
  code: string;
  topAgriculturalProducts: string[];
  foodManufacturingEmployees: number;
  foodManufacturingEstablishments: number;
  organicFarmCount: number;
  localSpecialtyFoods: string[];
  fdaRegisteredFacilities: number;
  description: string;
}

export const states: StateData[] = [
  {
    slug: 'alabama',
    name: 'Alabama',
    code: 'AL',
    topAgriculturalProducts: ['Broilers', 'Cotton', 'Cattle', 'Eggs', 'Peanuts'],
    foodManufacturingEmployees: 28400,
    foodManufacturingEstablishments: 420,
    organicFarmCount: 74,
    localSpecialtyFoods: ['White BBQ sauce', 'Lane cake', 'Boiled peanuts', 'Pecan pie'],
    fdaRegisteredFacilities: 1680,
    description: 'Alabama is a leading poultry and peanut producer in the Southeast. The state\'s food manufacturing sector centers on poultry processing, with a growing artisan sauce and condiment industry.',
  },
  {
    slug: 'alaska',
    name: 'Alaska',
    code: 'AK',
    topAgriculturalProducts: ['Seafood (wild salmon)', 'Greenhouse vegetables', 'Hay', 'Potatoes', 'Reindeer'],
    foodManufacturingEmployees: 16200,
    foodManufacturingEstablishments: 310,
    organicFarmCount: 22,
    localSpecialtyFoods: ['Smoked salmon', 'King crab', 'Akutaq (Eskimo ice cream)', 'Birch syrup'],
    fdaRegisteredFacilities: 920,
    description: 'Alaska\'s food industry revolves around wild-caught seafood, especially salmon and crab. The state leads in sustainable fisheries and cold-water processing operations.',
  },
  {
    slug: 'arizona',
    name: 'Arizona',
    code: 'AZ',
    topAgriculturalProducts: ['Lettuce', 'Dairy', 'Cotton', 'Cattle', 'Citrus'],
    foodManufacturingEmployees: 22800,
    foodManufacturingEstablishments: 580,
    organicFarmCount: 198,
    localSpecialtyFoods: ['Sonoran hot dogs', 'Prickly pear candy', 'Mesquite flour', 'Green chili salsa'],
    fdaRegisteredFacilities: 2340,
    description: 'Arizona is a major winter lettuce producer, supplying much of the nation\'s leafy greens from November through March. The state\'s food manufacturing includes tortilla production and desert-inspired specialty foods.',
  },
  {
    slug: 'arkansas',
    name: 'Arkansas',
    code: 'AR',
    topAgriculturalProducts: ['Broilers', 'Rice', 'Soybeans', 'Cotton', 'Catfish'],
    foodManufacturingEmployees: 42600,
    foodManufacturingEstablishments: 380,
    organicFarmCount: 68,
    localSpecialtyFoods: ['Cheese dip', 'Fried catfish', 'Purple hull peas', 'Chocolate gravy'],
    fdaRegisteredFacilities: 1520,
    description: 'Arkansas is the nation\'s top rice-producing state and a leading broiler producer. Tyson Foods, headquartered in Springdale, makes Arkansas a powerhouse in poultry processing.',
  },
  {
    slug: 'california',
    name: 'California',
    code: 'CA',
    topAgriculturalProducts: ['Almonds', 'Dairy', 'Grapes', 'Strawberries', 'Lettuce'],
    foodManufacturingEmployees: 196500,
    foodManufacturingEstablishments: 6820,
    organicFarmCount: 5842,
    localSpecialtyFoods: ['Sourdough bread', 'Avocado toast', 'California roll', 'Date shakes', 'Mission-style burritos'],
    fdaRegisteredFacilities: 28400,
    description: 'California is the nation\'s largest agricultural state, producing over a third of US vegetables and two-thirds of fruits and nuts. It leads the country in organic farming, food manufacturing employment, and FDA-registered food facilities.',
  },
  {
    slug: 'colorado',
    name: 'Colorado',
    code: 'CO',
    topAgriculturalProducts: ['Cattle', 'Dairy', 'Corn', 'Wheat', 'Hay'],
    foodManufacturingEmployees: 24100,
    foodManufacturingEstablishments: 920,
    organicFarmCount: 482,
    localSpecialtyFoods: ['Rocky Mountain oysters', 'Green chili', 'Bison burgers', 'Palisade peaches'],
    fdaRegisteredFacilities: 3680,
    description: 'Colorado\'s food industry spans cattle ranching on the eastern plains to craft food production in the Front Range. The state has a thriving natural and organic food sector, with many national brands headquartered along the Boulder-Denver corridor.',
  },
  {
    slug: 'connecticut',
    name: 'Connecticut',
    code: 'CT',
    topAgriculturalProducts: ['Dairy', 'Eggs', 'Greenhouse/Nursery', 'Tobacco', 'Apples'],
    foodManufacturingEmployees: 11200,
    foodManufacturingEstablishments: 420,
    organicFarmCount: 118,
    localSpecialtyFoods: ['New Haven-style pizza', 'Steamed cheeseburgers', 'Lobster rolls', 'Apple cider'],
    fdaRegisteredFacilities: 1840,
    description: 'Connecticut\'s food industry features specialty dairy, craft breweries, and a strong farm-to-table tradition. New Haven is renowned for its coal-fired pizza culture.',
  },
  {
    slug: 'delaware',
    name: 'Delaware',
    code: 'DE',
    topAgriculturalProducts: ['Broilers', 'Corn', 'Soybeans', 'Dairy', 'Watermelons'],
    foodManufacturingEmployees: 6800,
    foodManufacturingEstablishments: 120,
    organicFarmCount: 28,
    localSpecialtyFoods: ['Scrapple', 'Slippery dumplings', 'Peach pie', 'Blue crab'],
    fdaRegisteredFacilities: 620,
    description: 'Delaware\'s food sector is anchored by broiler chicken production on the Delmarva Peninsula. The state also has a growing craft food and beverage sector despite its small size.',
  },
  {
    slug: 'florida',
    name: 'Florida',
    code: 'FL',
    topAgriculturalProducts: ['Oranges', 'Sugarcane', 'Tomatoes', 'Strawberries', 'Bell peppers'],
    foodManufacturingEmployees: 52400,
    foodManufacturingEstablishments: 2680,
    organicFarmCount: 612,
    localSpecialtyFoods: ['Key lime pie', 'Cuban sandwich', 'Stone crab', 'Orange juice', 'Gator bites'],
    fdaRegisteredFacilities: 12200,
    description: 'Florida is the nation\'s leading citrus producer and a major winter vegetable supplier. The state\'s diverse food manufacturing sector ranges from juice processing to tropical fruit products and Latin-inspired foods.',
  },
  {
    slug: 'georgia',
    name: 'Georgia',
    code: 'GA',
    topAgriculturalProducts: ['Broilers', 'Cotton', 'Peanuts', 'Pecans', 'Blueberries'],
    foodManufacturingEmployees: 56800,
    foodManufacturingEstablishments: 1120,
    organicFarmCount: 142,
    localSpecialtyFoods: ['Peach cobbler', 'Vidalia onion rings', 'Boiled peanuts', 'Brunswick stew'],
    fdaRegisteredFacilities: 4680,
    description: 'Georgia is the nation\'s top broiler and peanut producer. The state\'s food manufacturing industry is among the largest in the Southeast, with major poultry processing, pecan shelling, and snack food operations.',
  },
  {
    slug: 'hawaii',
    name: 'Hawaii',
    code: 'HI',
    topAgriculturalProducts: ['Macadamia nuts', 'Coffee', 'Sugarcane', 'Pineapple', 'Tropical fruits'],
    foodManufacturingEmployees: 6400,
    foodManufacturingEstablishments: 320,
    organicFarmCount: 186,
    localSpecialtyFoods: ['Poke', 'Spam musubi', 'Haupia', 'Macadamia nut brittle', 'Shave ice'],
    fdaRegisteredFacilities: 1240,
    description: 'Hawaii\'s food industry showcases tropical agriculture including coffee, macadamia nuts, and exotic fruits. The state\'s unique fusion cuisine reflects its multicultural heritage.',
  },
  {
    slug: 'idaho',
    name: 'Idaho',
    code: 'ID',
    topAgriculturalProducts: ['Potatoes', 'Dairy', 'Cattle', 'Wheat', 'Barley'],
    foodManufacturingEmployees: 18200,
    foodManufacturingEstablishments: 380,
    organicFarmCount: 242,
    localSpecialtyFoods: ['Baked potatoes', 'Finger steaks', 'Huckleberry jam', 'Idaho fry sauce'],
    fdaRegisteredFacilities: 1620,
    description: 'Idaho produces about a third of the nation\'s potatoes. The state\'s food manufacturing sector is dominated by potato processing (frozen fries, dehydrated products) and dairy operations.',
  },
  {
    slug: 'illinois',
    name: 'Illinois',
    code: 'IL',
    topAgriculturalProducts: ['Corn', 'Soybeans', 'Hogs', 'Cattle', 'Wheat'],
    foodManufacturingEmployees: 68400,
    foodManufacturingEstablishments: 1920,
    organicFarmCount: 382,
    localSpecialtyFoods: ['Deep-dish pizza', 'Chicago hot dogs', 'Italian beef', 'Garrett popcorn'],
    fdaRegisteredFacilities: 7840,
    description: 'Illinois is a national hub for food processing and distribution. Chicago\'s historic role as the meatpacking capital has evolved into a diverse food manufacturing center with major confectionery, snack, and grain processing operations.',
  },
  {
    slug: 'indiana',
    name: 'Indiana',
    code: 'IN',
    topAgriculturalProducts: ['Corn', 'Soybeans', 'Hogs', 'Poultry', 'Dairy'],
    foodManufacturingEmployees: 42200,
    foodManufacturingEstablishments: 860,
    organicFarmCount: 196,
    localSpecialtyFoods: ['Sugar cream pie', 'Pork tenderloin sandwich', 'Persimmon pudding', 'Popcorn'],
    fdaRegisteredFacilities: 3420,
    description: 'Indiana is a major corn and soybean state with significant poultry and pork processing. The state\'s central location makes it a logistics hub for food distribution across the Midwest.',
  },
  {
    slug: 'iowa',
    name: 'Iowa',
    code: 'IA',
    topAgriculturalProducts: ['Corn', 'Hogs', 'Soybeans', 'Cattle', 'Eggs'],
    foodManufacturingEmployees: 38600,
    foodManufacturingEstablishments: 680,
    organicFarmCount: 348,
    localSpecialtyFoods: ['Loose meat sandwich', 'Corn on the cob', 'Pork chop on a stick', 'Scotcheroos'],
    fdaRegisteredFacilities: 2840,
    description: 'Iowa leads the nation in hog and egg production and is a top corn state. The state\'s food manufacturing centers on meat processing, with major packing plants and grain milling operations.',
  },
  {
    slug: 'kansas',
    name: 'Kansas',
    code: 'KS',
    topAgriculturalProducts: ['Wheat', 'Cattle', 'Corn', 'Sorghum', 'Soybeans'],
    foodManufacturingEmployees: 26800,
    foodManufacturingEstablishments: 480,
    organicFarmCount: 128,
    localSpecialtyFoods: ['Kansas City BBQ', 'Bierocks', 'Zwiebach bread', 'Sorghum syrup'],
    fdaRegisteredFacilities: 2120,
    description: 'Kansas is the nation\'s top wheat-producing state, earning its nickname as the Breadbasket of America. Major food manufacturing includes flour milling, beef processing, and pet food production.',
  },
  {
    slug: 'kentucky',
    name: 'Kentucky',
    code: 'KY',
    topAgriculturalProducts: ['Horses', 'Broilers', 'Cattle', 'Corn', 'Soybeans'],
    foodManufacturingEmployees: 22400,
    foodManufacturingEstablishments: 520,
    organicFarmCount: 98,
    localSpecialtyFoods: ['Hot brown sandwich', 'Bourbon balls', 'Burgoo stew', 'Beer cheese'],
    fdaRegisteredFacilities: 2080,
    description: 'Kentucky\'s food industry is closely tied to its bourbon heritage and Southern culinary traditions. The state has significant poultry processing and a growing specialty foods sector.',
  },
  {
    slug: 'louisiana',
    name: 'Louisiana',
    code: 'LA',
    topAgriculturalProducts: ['Sugarcane', 'Soybeans', 'Rice', 'Cotton', 'Crawfish'],
    foodManufacturingEmployees: 22600,
    foodManufacturingEstablishments: 620,
    organicFarmCount: 42,
    localSpecialtyFoods: ['Gumbo', 'Beignets', 'Crawfish etouffee', 'King cake', 'Boudin'],
    fdaRegisteredFacilities: 2680,
    description: 'Louisiana\'s food culture is world-famous, blending Cajun and Creole traditions. The state leads in sugarcane and crawfish production, with a vibrant specialty foods sector exporting hot sauces, seasonings, and prepared Cajun foods nationwide.',
  },
  {
    slug: 'maine',
    name: 'Maine',
    code: 'ME',
    topAgriculturalProducts: ['Potatoes', 'Blueberries', 'Dairy', 'Eggs', 'Maple syrup'],
    foodManufacturingEmployees: 8200,
    foodManufacturingEstablishments: 420,
    organicFarmCount: 524,
    localSpecialtyFoods: ['Lobster rolls', 'Whoopie pies', 'Wild blueberry pie', 'Maple candy'],
    fdaRegisteredFacilities: 1640,
    description: 'Maine is synonymous with lobster and wild blueberries. The state has one of the highest concentrations of organic farms per capita in the US and a strong artisan food tradition.',
  },
  {
    slug: 'maryland',
    name: 'Maryland',
    code: 'MD',
    topAgriculturalProducts: ['Broilers', 'Dairy', 'Corn', 'Soybeans', 'Nursery/Greenhouse'],
    foodManufacturingEmployees: 16800,
    foodManufacturingEstablishments: 540,
    organicFarmCount: 142,
    localSpecialtyFoods: ['Crab cakes', 'Old Bay seasoning', 'Smith Island cake', 'Pit beef'],
    fdaRegisteredFacilities: 2480,
    description: 'Maryland\'s food identity centers on Chesapeake Bay blue crabs and Old Bay seasoning. The state\'s food manufacturing includes seafood processing, spice blending, and snack production.',
  },
  {
    slug: 'massachusetts',
    name: 'Massachusetts',
    code: 'MA',
    topAgriculturalProducts: ['Cranberries', 'Dairy', 'Greenhouse/Nursery', 'Apples', 'Sweet corn'],
    foodManufacturingEmployees: 18400,
    foodManufacturingEstablishments: 680,
    organicFarmCount: 286,
    localSpecialtyFoods: ['Clam chowder', 'Boston cream pie', 'Baked beans', 'Fluffernutter'],
    fdaRegisteredFacilities: 3120,
    description: 'Massachusetts is a leading cranberry producer and home to a diverse food manufacturing sector. The state\'s innovation corridor fosters food tech startups alongside traditional New England food producers.',
  },
  {
    slug: 'michigan',
    name: 'Michigan',
    code: 'MI',
    topAgriculturalProducts: ['Dairy', 'Corn', 'Soybeans', 'Blueberries', 'Tart cherries'],
    foodManufacturingEmployees: 36800,
    foodManufacturingEstablishments: 1120,
    organicFarmCount: 412,
    localSpecialtyFoods: ['Detroit-style pizza', 'Cherry pie', 'Coney dogs', 'Pasties'],
    fdaRegisteredFacilities: 4280,
    description: 'Michigan leads the nation in tart cherry and blueberry production. The state\'s food manufacturing is diverse, including cereal (Battle Creek), pickle, and dairy processing.',
  },
  {
    slug: 'minnesota',
    name: 'Minnesota',
    code: 'MN',
    topAgriculturalProducts: ['Corn', 'Soybeans', 'Hogs', 'Dairy', 'Turkeys'],
    foodManufacturingEmployees: 42800,
    foodManufacturingEstablishments: 820,
    organicFarmCount: 586,
    localSpecialtyFoods: ['Hotdish', 'Wild rice', 'Juicy Lucy burger', 'Lefse'],
    fdaRegisteredFacilities: 3640,
    description: 'Minnesota is a top turkey and sugar beet producer with major food companies headquartered in the Twin Cities (General Mills, Hormel, Cargill). The state\'s food manufacturing sector is among the nation\'s largest.',
  },
  {
    slug: 'mississippi',
    name: 'Mississippi',
    code: 'MS',
    topAgriculturalProducts: ['Broilers', 'Soybeans', 'Cotton', 'Corn', 'Catfish'],
    foodManufacturingEmployees: 24200,
    foodManufacturingEstablishments: 340,
    organicFarmCount: 32,
    localSpecialtyFoods: ['Fried catfish', 'Mud pie', 'Tamales (Delta-style)', 'Comeback sauce'],
    fdaRegisteredFacilities: 1380,
    description: 'Mississippi is the nation\'s leading catfish producer, centered in the Delta region. The state\'s food manufacturing includes poultry processing, catfish farming, and Southern specialty foods.',
  },
  {
    slug: 'missouri',
    name: 'Missouri',
    code: 'MO',
    topAgriculturalProducts: ['Soybeans', 'Corn', 'Cattle', 'Hogs', 'Turkeys'],
    foodManufacturingEmployees: 36400,
    foodManufacturingEstablishments: 840,
    organicFarmCount: 218,
    localSpecialtyFoods: ['St. Louis-style ribs', 'Gooey butter cake', 'Toasted ravioli', 'Kansas City BBQ'],
    fdaRegisteredFacilities: 3240,
    description: 'Missouri\'s food manufacturing is anchored by meat processing and grain milling. Kansas City and St. Louis each contribute distinct culinary traditions, from BBQ to Italian-American foods.',
  },
  {
    slug: 'montana',
    name: 'Montana',
    code: 'MT',
    topAgriculturalProducts: ['Cattle', 'Wheat', 'Hay', 'Barley', 'Lentils'],
    foodManufacturingEmployees: 4200,
    foodManufacturingEstablishments: 240,
    organicFarmCount: 268,
    localSpecialtyFoods: ['Bison steaks', 'Huckleberry products', 'Flathead cherries', 'Elk jerky'],
    fdaRegisteredFacilities: 980,
    description: 'Montana\'s food industry emphasizes ranch-raised cattle and specialty grains. The state has a high concentration of organic farms and a growing artisan food sector featuring bison, huckleberry, and heritage grain products.',
  },
  {
    slug: 'nebraska',
    name: 'Nebraska',
    code: 'NE',
    topAgriculturalProducts: ['Cattle', 'Corn', 'Soybeans', 'Hogs', 'Wheat'],
    foodManufacturingEmployees: 38400,
    foodManufacturingEstablishments: 520,
    organicFarmCount: 148,
    localSpecialtyFoods: ['Runza sandwiches', 'Steak', 'Dorothy Lynch dressing', 'Kolaches'],
    fdaRegisteredFacilities: 2080,
    description: 'Nebraska is a top beef state, and its food manufacturing sector is dominated by meatpacking. The state processes more red meat than nearly any other state in the country.',
  },
  {
    slug: 'nevada',
    name: 'Nevada',
    code: 'NV',
    topAgriculturalProducts: ['Cattle', 'Dairy', 'Hay', 'Onions', 'Potatoes'],
    foodManufacturingEmployees: 6200,
    foodManufacturingEstablishments: 320,
    organicFarmCount: 42,
    localSpecialtyFoods: ['Basque lamb', 'Buffet cuisine', 'Pine nut cookies', 'Shrimp cocktail'],
    fdaRegisteredFacilities: 1480,
    description: 'Nevada\'s food industry is shaped by Las Vegas\'s massive hospitality sector. The state\'s food manufacturing focuses on bakery products, beverages, and prepared foods for the casino and restaurant industry.',
  },
  {
    slug: 'new-hampshire',
    name: 'New Hampshire',
    code: 'NH',
    topAgriculturalProducts: ['Dairy', 'Maple syrup', 'Apples', 'Greenhouse/Nursery', 'Hay'],
    foodManufacturingEmployees: 5400,
    foodManufacturingEstablishments: 280,
    organicFarmCount: 142,
    localSpecialtyFoods: ['Maple syrup', 'Apple cider donuts', 'Boiled dinner', 'Cider'],
    fdaRegisteredFacilities: 1040,
    description: 'New Hampshire\'s food sector features maple syrup production, craft beverages, and a thriving farm-to-table movement. The state has a high density of organic farms relative to its agricultural land.',
  },
  {
    slug: 'new-jersey',
    name: 'New Jersey',
    code: 'NJ',
    topAgriculturalProducts: ['Nursery/Greenhouse', 'Blueberries', 'Cranberries', 'Peaches', 'Tomatoes'],
    foodManufacturingEmployees: 32400,
    foodManufacturingEstablishments: 1240,
    organicFarmCount: 148,
    localSpecialtyFoods: ['Taylor ham/pork roll', 'Tomato pie', 'Salt water taffy', 'Disco fries'],
    fdaRegisteredFacilities: 5620,
    description: 'New Jersey, the Garden State, is a top blueberry and cranberry producer. Its proximity to New York City drives a large food manufacturing and distribution sector.',
  },
  {
    slug: 'new-mexico',
    name: 'New Mexico',
    code: 'NM',
    topAgriculturalProducts: ['Cattle', 'Dairy', 'Pecans', 'Chile peppers', 'Hay'],
    foodManufacturingEmployees: 8200,
    foodManufacturingEstablishments: 320,
    organicFarmCount: 122,
    localSpecialtyFoods: ['Green chile stew', 'Sopapillas', 'Biscochitos', 'Carne adovada'],
    fdaRegisteredFacilities: 1280,
    description: 'New Mexico is defined by its Hatch green chile, which anchors a unique food culture. The state produces the vast majority of US chile peppers and has a growing organic pecan industry.',
  },
  {
    slug: 'new-york',
    name: 'New York',
    code: 'NY',
    topAgriculturalProducts: ['Dairy', 'Apples', 'Corn', 'Cabbage', 'Maple syrup'],
    foodManufacturingEmployees: 56200,
    foodManufacturingEstablishments: 2840,
    organicFarmCount: 1124,
    localSpecialtyFoods: ['New York pizza', 'Bagels', 'Cheesecake', 'Buffalo wings', 'Black & white cookies'],
    fdaRegisteredFacilities: 11200,
    description: 'New York is the nation\'s third-largest dairy state and a major apple producer. New York City drives an enormous food manufacturing sector spanning bakeries, confectioneries, and ethnic food producers.',
  },
  {
    slug: 'north-carolina',
    name: 'North Carolina',
    code: 'NC',
    topAgriculturalProducts: ['Broilers', 'Hogs', 'Tobacco', 'Sweet potatoes', 'Turkeys'],
    foodManufacturingEmployees: 52400,
    foodManufacturingEstablishments: 1280,
    organicFarmCount: 312,
    localSpecialtyFoods: ['Pulled pork BBQ', 'Krispy Kreme donuts', 'Cheerwine', 'Livermush'],
    fdaRegisteredFacilities: 4680,
    description: 'North Carolina is a major hog and poultry state with deep BBQ traditions (Eastern vinegar vs. Lexington-style). The state\'s food manufacturing ranges from meat processing to major snack and beverage companies.',
  },
  {
    slug: 'north-dakota',
    name: 'North Dakota',
    code: 'ND',
    topAgriculturalProducts: ['Wheat', 'Soybeans', 'Corn', 'Sunflowers', 'Dry beans'],
    foodManufacturingEmployees: 6800,
    foodManufacturingEstablishments: 180,
    organicFarmCount: 218,
    localSpecialtyFoods: ['Knoephla soup', 'Fleischkuekle', 'Chokecherry jelly', 'Lefse'],
    fdaRegisteredFacilities: 840,
    description: 'North Dakota leads the nation in sunflower, flaxseed, and dry bean production. The state\'s food manufacturing centers on grain milling and oilseed processing.',
  },
  {
    slug: 'ohio',
    name: 'Ohio',
    code: 'OH',
    topAgriculturalProducts: ['Soybeans', 'Corn', 'Dairy', 'Eggs', 'Hogs'],
    foodManufacturingEmployees: 52600,
    foodManufacturingEstablishments: 1480,
    organicFarmCount: 428,
    localSpecialtyFoods: ['Cincinnati chili', 'Buckeyes (candy)', 'Sauerkraut balls', 'Pawpaw fruit'],
    fdaRegisteredFacilities: 5840,
    description: 'Ohio\'s food manufacturing is among the largest in the US, with major operations in snack foods (Akron), condiments (Cincinnati), and dairy processing. The state is a key Midwest agricultural producer.',
  },
  {
    slug: 'oklahoma',
    name: 'Oklahoma',
    code: 'OK',
    topAgriculturalProducts: ['Cattle', 'Wheat', 'Broilers', 'Hogs', 'Pecans'],
    foodManufacturingEmployees: 18200,
    foodManufacturingEstablishments: 420,
    organicFarmCount: 68,
    localSpecialtyFoods: ['Fried okra', 'Onion burgers', 'Pecan pie', 'Chicken-fried steak'],
    fdaRegisteredFacilities: 1840,
    description: 'Oklahoma\'s food industry centers on cattle ranching and wheat farming. The state has a growing pecan industry and a distinctive comfort food culture influenced by both Southern and Southwest traditions.',
  },
  {
    slug: 'oregon',
    name: 'Oregon',
    code: 'OR',
    topAgriculturalProducts: ['Dairy', 'Cattle', 'Hay', 'Hazelnuts', 'Grass seed'],
    foodManufacturingEmployees: 22800,
    foodManufacturingEstablishments: 1080,
    organicFarmCount: 824,
    localSpecialtyFoods: ['Marionberry pie', 'Tillamook cheese', 'Hazelnuts', 'Voodoo Doughnuts'],
    fdaRegisteredFacilities: 3840,
    description: 'Oregon produces 99% of the nation\'s hazelnuts and has one of the highest organic farm concentrations in the US. The state\'s food manufacturing includes cheese, specialty beverages, and artisan foods.',
  },
  {
    slug: 'pennsylvania',
    name: 'Pennsylvania',
    code: 'PA',
    topAgriculturalProducts: ['Dairy', 'Mushrooms', 'Eggs', 'Corn', 'Poultry'],
    foodManufacturingEmployees: 62400,
    foodManufacturingEstablishments: 2120,
    organicFarmCount: 642,
    localSpecialtyFoods: ['Philly cheesesteak', 'Shoofly pie', 'Scrapple', 'Soft pretzels', 'Whoopie pies'],
    fdaRegisteredFacilities: 7640,
    description: 'Pennsylvania produces more mushrooms than any other state and is a top dairy and egg state. The state\'s food manufacturing sector is enormous, spanning snack foods (Hershey), dairy, meat, and bakery products.',
  },
  {
    slug: 'rhode-island',
    name: 'Rhode Island',
    code: 'RI',
    topAgriculturalProducts: ['Nursery/Greenhouse', 'Dairy', 'Sweet corn', 'Potatoes', 'Apples'],
    foodManufacturingEmployees: 3800,
    foodManufacturingEstablishments: 160,
    organicFarmCount: 38,
    localSpecialtyFoods: ['Clam cakes', 'Coffee milk', 'Stuffies', 'Del\'s Lemonade'],
    fdaRegisteredFacilities: 640,
    description: 'Rhode Island has a distinctive food culture featuring coffee milk (the state drink) and clam cakes. Despite its small size, the state has an active seafood processing and specialty food sector.',
  },
  {
    slug: 'south-carolina',
    name: 'South Carolina',
    code: 'SC',
    topAgriculturalProducts: ['Broilers', 'Turkeys', 'Cotton', 'Soybeans', 'Peaches'],
    foodManufacturingEmployees: 22600,
    foodManufacturingEstablishments: 520,
    organicFarmCount: 86,
    localSpecialtyFoods: ['Shrimp and grits', 'She-crab soup', 'Frogmore stew', 'Pimento cheese'],
    fdaRegisteredFacilities: 2140,
    description: 'South Carolina\'s food heritage blends Lowcountry cuisine with Southern traditions. The state\'s food manufacturing includes poultry processing, snack foods, and a growing artisan food sector.',
  },
  {
    slug: 'south-dakota',
    name: 'South Dakota',
    code: 'SD',
    topAgriculturalProducts: ['Cattle', 'Corn', 'Soybeans', 'Wheat', 'Sunflowers'],
    foodManufacturingEmployees: 8400,
    foodManufacturingEstablishments: 220,
    organicFarmCount: 182,
    localSpecialtyFoods: ['Chislic', 'Kuchen', 'Indian tacos', 'Pheasant'],
    fdaRegisteredFacilities: 920,
    description: 'South Dakota\'s food industry centers on cattle ranching and grain production. The state has growing organic farming and a unique food culture influenced by German-Russian and Native American traditions.',
  },
  {
    slug: 'tennessee',
    name: 'Tennessee',
    code: 'TN',
    topAgriculturalProducts: ['Cattle', 'Broilers', 'Soybeans', 'Cotton', 'Corn'],
    foodManufacturingEmployees: 34200,
    foodManufacturingEstablishments: 780,
    organicFarmCount: 128,
    localSpecialtyFoods: ['Nashville hot chicken', 'Memphis BBQ', 'Moon Pies', 'Goo Goo Clusters'],
    fdaRegisteredFacilities: 3280,
    description: 'Tennessee\'s food scene spans Memphis BBQ to Nashville hot chicken. The state\'s food manufacturing includes meat processing, snack foods (Moon Pies, Goo Goo Clusters), and the Jack Daniel\'s distillery.',
  },
  {
    slug: 'texas',
    name: 'Texas',
    code: 'TX',
    topAgriculturalProducts: ['Cattle', 'Cotton', 'Dairy', 'Broilers', 'Corn'],
    foodManufacturingEmployees: 98600,
    foodManufacturingEstablishments: 3420,
    organicFarmCount: 428,
    localSpecialtyFoods: ['Texas BBQ brisket', 'Kolaches', 'Queso', 'Chicken-fried steak', 'Breakfast tacos'],
    fdaRegisteredFacilities: 14200,
    description: 'Texas leads the nation in cattle production and is a major agricultural state. Its enormous food manufacturing sector spans meat processing, tortilla production, snack foods, and beverages, supported by a growing Hispanic food market.',
  },
  {
    slug: 'utah',
    name: 'Utah',
    code: 'UT',
    topAgriculturalProducts: ['Cattle', 'Dairy', 'Hay', 'Turkeys', 'Barley'],
    foodManufacturingEmployees: 12400,
    foodManufacturingEstablishments: 480,
    organicFarmCount: 98,
    localSpecialtyFoods: ['Fry sauce', 'Funeral potatoes', 'Jell-O salads', 'Pastrami burgers'],
    fdaRegisteredFacilities: 1820,
    description: 'Utah\'s food industry includes dairy processing, candy manufacturing, and a growing natural foods sector. The state has unique food traditions influenced by its pioneer heritage.',
  },
  {
    slug: 'vermont',
    name: 'Vermont',
    code: 'VT',
    topAgriculturalProducts: ['Dairy', 'Maple syrup', 'Cattle', 'Hay', 'Apples'],
    foodManufacturingEmployees: 5800,
    foodManufacturingEstablishments: 380,
    organicFarmCount: 712,
    localSpecialtyFoods: ['Maple syrup', 'Cheddar cheese', 'Ben & Jerry\'s ice cream', 'Apple cider'],
    fdaRegisteredFacilities: 1180,
    description: 'Vermont produces more maple syrup than any other state and has the highest concentration of organic farms per capita in the nation. The state\'s food identity centers on artisan dairy (Cabot, Ben & Jerry\'s) and farm-to-table tradition.',
  },
  {
    slug: 'virginia',
    name: 'Virginia',
    code: 'VA',
    topAgriculturalProducts: ['Broilers', 'Cattle', 'Dairy', 'Soybeans', 'Turkeys'],
    foodManufacturingEmployees: 28200,
    foodManufacturingEstablishments: 920,
    organicFarmCount: 312,
    localSpecialtyFoods: ['Virginia ham', 'Peanut soup', 'Oysters', 'Brunswick stew'],
    fdaRegisteredFacilities: 3840,
    description: 'Virginia\'s food heritage includes Smithfield ham, peanuts, and Chesapeake Bay oysters. The state\'s food manufacturing is diverse, with poultry processing, beverage production, and a thriving artisan food scene.',
  },
  {
    slug: 'washington',
    name: 'Washington',
    code: 'WA',
    topAgriculturalProducts: ['Apples', 'Dairy', 'Wheat', 'Potatoes', 'Hops'],
    foodManufacturingEmployees: 42600,
    foodManufacturingEstablishments: 1420,
    organicFarmCount: 986,
    localSpecialtyFoods: ['Geoduck', 'Rainier cherries', 'Walla Walla onions', 'Smoked salmon'],
    fdaRegisteredFacilities: 5240,
    description: 'Washington produces more apples than any other state and is a leading dairy and wheat state. The Pacific Northwest food culture emphasizes local, organic, and sustainably sourced ingredients.',
  },
  {
    slug: 'west-virginia',
    name: 'West Virginia',
    code: 'WV',
    topAgriculturalProducts: ['Broilers', 'Cattle', 'Turkeys', 'Hay', 'Apples'],
    foodManufacturingEmployees: 4800,
    foodManufacturingEstablishments: 180,
    organicFarmCount: 52,
    localSpecialtyFoods: ['Pepperoni rolls', 'Ramps', 'Apple butter', 'Buckwheat pancakes'],
    fdaRegisteredFacilities: 720,
    description: 'West Virginia\'s food culture features Appalachian traditions like ramps (wild leeks), pepperoni rolls (the state\'s unofficial food), and heritage apple varieties. The state has a small but growing artisan food sector.',
  },
  {
    slug: 'wisconsin',
    name: 'Wisconsin',
    code: 'WI',
    topAgriculturalProducts: ['Dairy', 'Corn', 'Soybeans', 'Cattle', 'Cranberries'],
    foodManufacturingEmployees: 68200,
    foodManufacturingEstablishments: 1480,
    organicFarmCount: 1186,
    localSpecialtyFoods: ['Cheese curds', 'Bratwurst', 'Butter burgers', 'Kringle pastry'],
    fdaRegisteredFacilities: 5440,
    description: 'Wisconsin is America\'s Dairyland, leading the nation in cheese production and ranking second in dairy overall. The state\'s food manufacturing is dominated by cheese and dairy processing, along with meat, sausage, and cranberry products.',
  },
  {
    slug: 'wyoming',
    name: 'Wyoming',
    code: 'WY',
    topAgriculturalProducts: ['Cattle', 'Hay', 'Sugar beets', 'Barley', 'Wheat'],
    foodManufacturingEmployees: 1800,
    foodManufacturingEstablishments: 120,
    organicFarmCount: 38,
    localSpecialtyFoods: ['Bison jerky', 'Elk steaks', 'Huckleberry jam', 'Trout'],
    fdaRegisteredFacilities: 420,
    description: 'Wyoming\'s food industry is anchored by cattle ranching. The state has a growing specialty meats sector featuring bison and elk, along with artisan products using wild huckleberries and other foraged ingredients.',
  },
  {
    slug: 'district-of-columbia',
    name: 'District of Columbia',
    code: 'DC',
    topAgriculturalProducts: ['Urban farms', 'Rooftop gardens', 'Microgreens', 'Herbs', 'Honey'],
    foodManufacturingEmployees: 2400,
    foodManufacturingEstablishments: 180,
    organicFarmCount: 8,
    localSpecialtyFoods: ['Half-smoke sausage', 'Mumbo sauce', 'Ethiopian cuisine', 'Cherry blossom treats'],
    fdaRegisteredFacilities: 840,
    description: 'Washington, D.C.\'s food scene reflects its cosmopolitan character, with Ethiopian cuisine as a hallmark. The District has a growing urban farming movement and food tech sector focused on food policy and innovation.',
  },
];

export function getAllStates(): StateData[] {
  return states;
}

export function getStateBySlug(slug: string): StateData | undefined {
  return states.find((s) => s.slug === slug);
}
